### ISSUE TITLE
Missing file after installation : /run/defectdojo/uwsgi_server" failed (2: No such file or directory) in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by Greenmouse94** [DefectDojo/godojo#12]
Hello !

I encountered this error after installing DefectDojo and tried to restart Nginx. Do you know what could be the problem ? 

mai 28 15:55:47 test-VirtualBox nginx[91407]: nginx: [emerg] open() "/run/defectdojo/uwsgi_server" failed (2: No such file or directory) in /etc/nginx/nginx.conf

Thank you.

**Comment by mtesauro** [comment]
Can you let me know what kind of install you did?  Numbered release, head of a branch or a commit?

Basically the first couple of lines [here](https://github.com/DefectDojo/godojo/blob/master/example_dojoConfig.yml#L17)

Also, the output of ./godojo --version would be helpful.

If you're installing from the dev branch of DefectDojo which is having a bunch of changes for version 2.0 of DefectDojo, one of those files may have changed - either nginx.conf or uwsgi_server.  Once I know more about the kind of install you did, I can better answer.

**Comment by Greenmouse94** [comment]
Hello, 

Thank you for your reply.

I did not change the default configuration file, I think it was the version 1.15.0 and the branch dev, I think. But once the installation was completed and successful, I was not able to connect to (for example) localhost:8080, so I installed Nginx and replaced the nginx config with the one from the DefectDojo directory, and once I restarted Nginx I had this error.

Best regards.

**Comment by mtesauro** [comment]
So, I added some scripts to this repo to use to start the installation that godojo does for you.

You can find those at https://github.com/DefectDojo/godojo/tree/master/scripts

If you want to use nginx to front DefectDojo, there's a link on how to do that on the readme in the scripts directory.  Basically, you just need to setup nginx as a reverse proxy of DefectDojo.

**Comment by mtesauro** [comment]
BTW, that error looks like you might have pulled the nginx config from the main  DefectDojo repo.

If you want your DefectDojo to replicate the setup of docker-compose/k8s, you'll need to pull the relevant bits out of the nginx entrypoint script:
https://github.com/DefectDojo/django-DefectDojo/blob/master/docker/entrypoint-nginx.sh
and the uwsgi entrypoint script as well:
https://github.com/DefectDojo/django-DefectDojo/blob/master/docker/entrypoint-uwsgi.sh

HTH
