### ISSUE TITLE
Unable to start defect dojo after installation using godojo

### ISSUE THREAD

**Issue by Testteam20k** [DefectDojo/godojo#13]
Tried installing defect dojo using godojo in Ubuntu.
The installation was successful. but  could not launch defect dojo post installation.
Please give us steps to start defect dojo web app (UI) after installation using godojo.

**Comment by mtesauro** [comment]
Added those to the repo, look at the scripts directory in the repo:

https://github.com/DefectDojo/godojo/tree/master/scripts

HTH
