### ISSUE TITLE
ERROR: Failed to run OS command, error was: exit status 1 - godojo 1.1.3

### ISSUE THREAD

**Issue by bl4ckbo7** [DefectDojo/godojo#19]
Hey what's with this error when running this latest version of godojo??

![image](https://user-images.githubusercontent.com/24606406/124349468-d1e84f80-dbf7-11eb-827d-daf0a5070e22.png)

##############################################################################
  ERROR: Failed to run OS command, error was: exit status 1
##############################################################################

**Comment by mtesauro** [comment]
Need a bit more info to help you out.

What OS are you doing this on?  What version of DefectDojo are you trying to install?  A numbered release?  which one?

Also, if you tail the log files that get created in the logs directory where you ran godojo, you'll see the exact command that failed and can try that in the same terminal/shell session you can godojo in.  Do something like:

`tail logs/"cmd-output_*`
  and
`tail logs/`

Ideally, drop the output of those two tail command here and I'll have a much better chance of being able to help you with that error.

**Comment by bl4ckbo7** [comment]
Oh thanks. Will get back to you soon..

**Comment by bl4ckbo7** [comment]
OS: Ubuntu 20.04
DefectDojo: 2.0.3 (release)
Python: 3
godojo: 1.1.3

![image](https://user-images.githubusercontent.com/24606406/124889608-efdef700-dfdf-11eb-9292-b7f801d26c25.png)

![image](https://user-images.githubusercontent.com/24606406/124889783-16049700-dfe0-11eb-9586-bf6fb202f221.png)

Thanks.

**Comment by bl4ckbo7** [comment]
Output of this command:
`cd /opt/dojo/django-DefectDojo && source ../bin/activate && python3 manage.py loaddata product_type`

![image](https://user-images.githubusercontent.com/24606406/124910845-ba90d400-dff4-11eb-969f-52d74c925199.png)

**Comment by mtesauro** [comment]
Looks like I should have pushed my current changes up sooner.  I just replicated your setup and the install worked for me.

Granted, I'm using 1.1.4 of godojo (which hasn't been released as I'm writing this)

I'll knock out a release tonight.  Grab 1.1.4 once it is up and it should work for you.

Hoped to get  a bit more cleanup done before I pushed this but no worries.

**Comment by mtesauro** [comment]
Just re-tested 1.1.4 before I do the release and success :+1: 

![image](https://user-images.githubusercontent.com/3422419/125015753-bc2ebc00-e035-11eb-9462-6dbe0781cb9a.png)

**Comment by mtesauro** [comment]
Closing this now that 1.1.4 is released - see https://github.com/DefectDojo/godojo/releases/tag/1.1.4

Thanks for providing the additional info that allowed me to validate that 1.1.4 would work in your setup.

**Comment by bl4ckbo7** [comment]
Thank you. It worked!
