### ISSUE TITLE
Error Installing via GoDojo

### ISSUE THREAD

**Issue by Mijobar** [DefectDojo/godojo#22]
![image](https://user-images.githubusercontent.com/6438286/126368823-62f90a32-fd46-4e1e-98fd-bca60885471e.png)

Looking in /opt/dojo/django-DefectDojo/dojo/fixtures, the role.json file is missing? 

Any thoughts? Thanks!

**Comment by mtesauro** [comment]
Thanks for reporting the issue.

Fortunately (or maybe unfortunately) this is a known issue. I have a fix in the dev branch that I need to do a bit more testing of before I cut a new release.  I'm addressing the role issue (only needs to be applied for 2.x.x or later) and an issue with Python 3.8 (the language had a bug that effected 1 line of Dojo code)

Look for a version 1.1.6 in the next couple of days.

**Comment by mtesauro** [comment]
Going to co ahead and close this as I just pushed up version 1.1.6 - https://github.com/DefectDojo/godojo/releases/tag/1.1.6

Best of luck!

**Comment by mtesauro** [comment]
Going to co ahead and close this as I just pushed up version 1.1.6 - https://github.com/DefectDojo/godojo/releases/tag/1.1.6

Best of luck!

**Comment by Mijobar** [comment]
Wanted to let you know that the new release installation completed successfully! Thanks so much!

**Comment by mtesauro** [comment]
Glad it worked for you! :+1:
