### ISSUE TITLE
ERROR: Error attempting to install Dojo from a release

### ISSUE THREAD

**Issue by ganesh2183** [DefectDojo/godojo#25]
While running godojo in Virtualbox VM Debian 10 (guest OS)

sudo ./godojo

Getting error as,
ERROR: Error attempting to install Dojo from a release was: Get "https://github.com/DefectDojo/django-DefectDojo/archive/2.0.3.tar.gz": read TCP 10.0.2.15:35100->140.82.112.4:443: read: connection reset by peer

![16297863443763089360762484873334](https://user-images.githubusercontent.com/41476297/130566936-1da2c2f9-f136-4fc7-9b99-aebb806f684d.jpg)

How to fix this issue

**Comment by mtesauro** [comment]
That error occurs when godojo can't reach the Github servers.  It was trying to download the release from the Github release page on the django-Defectdojo repo.

If that happens, the easiest thing is to try again assuming it was just a network blimp (aka a temporary error).

Alternatively, you can try to browse to the link in the error message above from that same server/VM (wget/curl) or even try the second IP address 14.082.112.4 with curl/wget.  If you have a UI on the server, you can try the link in a 'proper' browser.

godojo requires access to github.com to be able to either download a specific release or commit from the git repo.

HTH

**Comment by mtesauro** [comment]
Going to assume you re-ran godojo after sorting out the network issue and close this.
