### ISSUE TITLE
Unable to login if using any version >2.0.3

### ISSUE THREAD

**Issue by giveen** [DefectDojo/godojo#28]
If I install using godojo any version other than v2.0.3, it results in my password for my admin user being unable to login.

System: Ubuntu 18 LTS and 20 LTS
PostgreSQL 14 (I have also tried 10-13)

**dojoConfig.yml**
```Install:
  Version: "2.1.0" # DD_Version - Release version of DefectDojo from Github Releases
  SourceInstall: false # DD_SourceInstall - Boolean if a source install is desired (vs a release)
  # If ^ is true, a souce code install will occur overriding the release version provided
  SourceBranch: "release" # DD_SourceBranch - The branch's HEAD to be checked out if SourceInstall is true
```
```Admin:
    User: "issmonitor" # DD_ADMIN_User - Admin user for the DefectDojo web app
    Pass: "J**********************$" # DD_ADMIN_Pass - Password for the DefectDojo web app admin user Note: set to 24 random characters
    Email: "admin@localhost" # DD_ADMIN_Email - Email address for the web app admin user
    First: "Default" # DD_ADMIN_First - Web app admin users's first name
    Last: "Admin" # DD_ADMIN_Last - Web app admin users's last name
    Others: "" # DD_ADMIN_Others - List of additional DefectDojo web app admins e.g. username1:pass1,username2:pass2
```
![1](https://user-images.githubusercontent.com/1180939/136856091-ff3f690e-be78-47c5-9672-dff3be60fe8b.PNG)

Database shows my username is correct and in the database

![2](https://user-images.githubusercontent.com/1180939/136856119-3fa98fdf-0340-4572-b745-820df4783c22.PNG)

**runtime-install-config.yml** shows my information matches what I put into my dojoConfig.yml

![3](https://user-images.githubusercontent.com/1180939/136856221-7d1f1909-4330-4b77-93d2-a0e95296cbb9.PNG)

**Comment by giveen** [comment]
I was able to identify the source of the issue.
![44](https://user-images.githubusercontent.com/1180939/137037562-3779335f-1e66-4778-acb9-d078fd3c8991.PNG)


By manually running the script, setting my password in a single quote ', I was able to change the password and login

```cd /opt/dojo/django-DefectDojo && source ../bin/activate && /opt/dojo/django-DefectDojo/setup-superuser.expect issmonitor 'Pasa$df543q5xdfasr34' spawn python3 manage.py changepassword issmonitor```

**Comment by mtesauro** [comment]
Thanks for pointing this out.  Missed replying to this as I was traveling tons in November. I also found the same issue while on the road.  Look for a new version that fixed that problem.  The fix I included escapes problematic characters for Bash and uses double quotes on that argument to the expect script.

I'll leave this open till I release the new version so I have a hard reminder :smiley:

**Comment by mtesauro** [comment]
Oh, and there's some Postgres specific content in this PR I did to the community-contrib repo as well that may help you out:
https://github.com/DefectDojo/Community-Contribs/tree/master/CentOS-7-deploy

**Comment by giveen** [comment]
Thanks @mtesauro for looking at this bug. I do have one other issue when installing anything >2.2.1, which has to do with Python packages. I'll narrow down the issue and see if I can post a issue report on it.

Unfortunately in my environment, until our server engineers nail down a specific patch procedures for Docker, we cannot use it till then.

**Comment by mtesauro** [comment]
Ohh, that issue is also wrapped into the new release.  

For a period of time, DefectDojo had to use the older/now deprecated resolver for PIP.  That's been removed so PIP uses the default/new resolver in the release I have queued up.

Give me a day or two and I'll knock out the release.

**Comment by mtesauro** [comment]
Man, this week got busy for me.  Took more then a day or two but the 1.1.7 release should have the fixes you were looking for:

https://github.com/DefectDojo/godojo/releases/tag/1.1.7

I'm going to go ahead and close this.  Feel free to open a new issue if I missed something.

**Comment by mtesauro** [comment]
For people that find this later, there's info on resetting the default admin user's password in the comments of issue #51
