### ISSUE TITLE
godojo terminating with context canceled

### ISSUE THREAD

**Issue by vlgarant** [DefectDojo/godojo#38]
When i run godojo -default, it run to completion, but if i run it twice without arguments (one to create config, then the run) it just terminate after "downloading the source" and the logs show : 
error closing response Error was "context canceled"

this prevents me from using any release other than 2.0.3 :(

**Comment by mtesauro** [comment]
So, a couple of things:

(1) What version of godojo are you using?  There was a [new version](https://github.com/DefectDojo/godojo/releases/tag/1.1.7) that updated the default version to DefectDojo 2.4.1 recently (6 days ago as of when I'm typing).

(2) The error you're seeing is the connection to Github to download the DefectDojo release timing out. This is controlled in Go by the context package so that's why you see "context canceled".  The max time for a http client request was reached.

(3) Whatever is in the dojoConfig.yml - you can edit it to any existing version of DefectDojo and godojo will fetch that version.  So, with whatever version of godojo you have currently.  If you just change the first few non-comment lines of the dojoConfig.yml to look like:

```
$ head -n 20 dojoConfig.yml | tail -n 5
Install:
  Version: "2.4.1" # DD_Version - Release version of DefectDojo from Github Releases
  SourceInstall: false # DD_SourceInstall - Boolean if a source install is desired (vs a release)
  # If ^ is true, a souce code install will occur overriding the release version provided
  SourceBranch: "dev" # DD_SourceBranch - The branch's HEAD to be checked out if SourceInstall is true
```

So whatever DefectDojo version number is put in the `Version: ` above will be downloaded from DefectDojo's releases in Github.

Make that change to dojoConfig.yml and re-run `godojo` to get 2.4.1 installed.

That's the best I can do unless you want to tail the two log files (cmd-output* and dojo-install-*) and drop that info here.

HTH

**Comment by mtesauro** [comment]
Tested your situation and realized that bindata.go (where the embedded data lives) wasn't re-generated when I updated the default version in embd/dojoConfig.yml.  That's been fixed and an updated 1.1.7 release binary added to the releases.

**Comment by pavan3534** [comment]
@mtesauro - I am using v1.1.7 godojo installer. I am facing the "Error was: context canceled". Can you please look into the logs below.
TRACE:   2022/08/22 17:31:43 Logging established, trace log begins here
INFO:    2022/08/22 17:31:43 SECTION: Starting the dojo install at Mon Aug 22, 2022 17:31:43 IST
TRACE:   2022/08/22 17:31:43 Creating log file for OS command output for debugging reasons
TRACE:   2022/08/22 17:31:43 Successfully created OS Command log file at logs/cmd-output_1661169703135789831.log
TRACE:   2022/08/22 17:31:43 Writing out the runtime install configuration file
INFO:    2022/08/22 17:31:43 SECTION: Determining OS for installation
TRACE:   2022/08/22 17:31:43 Determining OS based on GOOS: linux
TRACE:   2022/08/22 17:31:43 OS determined to be Linux
TRACE:   2022/08/22 17:31:43 Determining what Linux distro is the target OS
TRACE:   2022/08/22 17:31:43 Determining Linux distro from /etc/os-release
INFO:    2022/08/22 17:31:43 OS was determined to be Linux, Ubuntu:22.04
INFO:    2022/08/22 17:31:43 DefectDojo installation on this OS is supported, continuing
INFO:    2022/08/22 17:31:43 SECTION: Bootstrapping the godojo installer
INFO:    2022/08/22 17:31:47 Boostraping godojo installer complete
INFO:    2022/08/22 17:31:47 SECTION: Checking for Python 3
INFO:    2022/08/22 17:31:47 Python 3 found, install can continue
INFO:    2022/08/22 17:31:47 SECTION: Downloading the source for DefectDojo
TRACE:   2022/08/22 17:31:47 Determining if this is a source or release install: SourceInstall is false
TRACE:   2022/08/22 17:31:47 Dojo will be installed from a release tarball
INFO:    2022/08/22 17:31:47 Downloading the configured release of DefectDojo => version 2.4.1
TRACE:   2022/08/22 17:31:47 Creating the Dojo root directory if it doesn't exist already
TRACE:   2022/08/22 17:31:47 Relese download list is https://github.com/DefectDojo/django-DefectDojo/archive/2.4.1.tar.gz
TRACE:   2022/08/22 17:31:47 File path to write tarball is /opt/dojo/dojo-v2.4.1.tar.gz
TRACE:   2022/08/22 17:31:47 http.Client timeout set to 60 seconds for release download
TRACE:   2022/08/22 17:31:47 Downloading release from https://github.com/DefectDojo/django-DefectDojo/archive/2.4.1.tar.gz
TRACE:   2022/08/22 17:31:49 Status of http.Client response was 200 OK
TRACE:   2022/08/22 17:31:49 Creating file for downloaded tarball
TRACE:   2022/08/22 17:31:49 Writing downloaded content to tarball file
TRACE:   2022/08/22 17:31:59 Extracting tarball into the Dojo source directory
TRACE:   2022/08/22 17:32:00 Renaming source directory to the non-versioned name
INFO:    2022/08/22 17:32:00 Successfully downloaded and extracted the DefectDojo release file
TRACE:   2022/08/22 17:32:00 Error closing response.
Error was: context canceled.

**Comment by mtesauro** [comment]
Looks like some kind of network error with the download - possibly like the connection to Github to download the release couldn't be closed.

I'll look into it and re-open this issue for tracking purposes.

**Comment by mkraats** [comment]
I'm experiencing the exact same problem. I've tried this on Ubuntu and Rocky. The installer fails with:

TRACE:   2022/10/14 10:22:40 Downloading release from https://github.com/DefectDojo/django-DefectDojo/archive/2.4.1.tar.gz
TRACE:   2022/10/14 10:22:41 Status of http.Client response was 200 OK
TRACE:   2022/10/14 10:22:41 Creating file for downloaded tarball
TRACE:   2022/10/14 10:22:41 Writing downloaded content to tarball file
TRACE:   2022/10/14 10:22:44 Extracting tarball into the Dojo source directory
TRACE:   2022/10/14 10:22:45 Renaming source directory to the non-versioned name
INFO:    2022/10/14 10:22:45 Successfully downloaded and extracted the DefectDojo release file
TRACE:   2022/10/14 10:22:45 Error closing response.

**Comment by mtesauro** [comment]
In recent versions, I increased the timeout on the downloads that godojo does.  I'd suggest trying the latest version of godojo  - v1.1.9
