### ISSUE TITLE
Issues in Godojo Installation

### ISSUE THREAD

**Issue by LearningAbhi** [DefectDojo/godojo#43]
Hi Team,
I am trying to install godojo in my Ubuntu 20.04.4. 
While running the godojo installer , I am getting below error.
![Screenshot 2022-04-27 113432](https://user-images.githubusercontent.com/44859656/165451848-33b59c28-1d8a-4a58-ad11-e2bda9e84f58.png)

The yarn package is getting installed properly via terminal, but when I am trying to call the same from dojoConfig.yml file I am getting this error.
Please guide me to resolve the same issue so that I will be able to install the godojo app.

TIA

**Comment by giveen** [comment]
User have rights to do updates?

**Comment by LearningAbhi** [comment]
Yes. Able to apt update manually, but not able to when calling the same from dojoConfig.yml file.

**Comment by giveen** [comment]
> Yes. Able to apt update manually, but not able to when calling the same from dojoConfig.yml file.

I was able to duplicate your error.

And after trying a manual update:

![image](https://user-images.githubusercontent.com/1180939/167475336-3e1dd738-7687-4aef-bb54-e200b913fff7.png)


So it looks like something has a lock on apt update, so try getting those updated first, try a reboot first and then updating by hand first.

**Comment by mtesauro** [comment]
Yes, the calls to `apt` from godojo will fail if someone else/some other process has a lock on apt.

A restart/reboot isn't strictly necessary but is probably quicker if you aren't super familiar with debugging issues with apt locks.
