### ISSUE TITLE
Node.js 12 is no longer supported

### ISSUE THREAD

**Issue by noloader** [DefectDojo/godojo#50]
I'm running `godojo` from the command line. While inspecting the output of the commands log file I see this:

```
[godojo] # curl -sL https://rpm.nodesource.com/setup_12.x | bash - 

================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 12.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.
  ...
```

It may be wise to use the Node.js provided by the distribution instead of fetching an unsupported version. Using a distro's version should ensure updates are available and vulnerabilities are patched.

Based on some testing, it looks like `https://rpm.nodesource.com/setup_18.x` is available nowadays from nodesource.com.

**Comment by mtesauro** [comment]
That change can be accommodated by changing the appropriate line in dojoConfig.yml aka `NodeURL:` see https://github.com/DefectDojo/godojo/blob/master/example_dojoConfig.yml#L162

Note that you have an RPM-based URL above and would need a .deb-based URL if installing on deb-based systems.
