### ISSUE TITLE
dojodbusr user appears to have too many privileges

### ISSUE THREAD

**Issue by noloader** [DefectDojo/godojo#54]
When I look at the Access Privileges on my PostgreSQL database after running the installer I see this:

```
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges    
-----------+----------+----------+-------------+-------------+------------------------
 dojodb    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres          +
           |          |          |             |             | postgres=CTc/postgres +
           |          |          |             |             | dojodbusr=CTc/postgres
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres           +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres           +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)
```

Intuitively, the admin account `postgres` and the dojo user account `dojodbusr` have the same privileges. Something seems sideways.

According to PostgreSQL manual, [Section 5.7. Privileges](https://www.postgresql.org/docs/current/ddl-priv.html), the privileges `CTc` are "All Privileges" on the Database. I don't think `dojodbusr` should have that kind of power. Shooting from the hip, they should have `rawTX`, which is SELECT, INSERT, UPDATE, TRIGGER and EXECUTE on the Tables.

Privilege | Abbreviation | Applicable Object Types
-- | -- | --
SELECT | r (“read”) | LARGE OBJECT, SEQUENCE, TABLE (and table-like objects), table column
INSERT | a (“append”) | TABLE, table column
UPDATE | w (“write”) | LARGE OBJECT, SEQUENCE, TABLE, table column
DELETE | d | TABLE
TRUNCATE | D | TABLE
REFERENCES | x | TABLE, table column
TRIGGER | t | TABLE
CREATE | C | DATABASE, SCHEMA, TABLESPACE
CONNECT | c | DATABASE
TEMPORARY | T | DATABASE
EXECUTE | X | FUNCTION, PROCEDURE
USAGE | U | DOMAIN, FOREIGN DATA WRAPPER, FOREIGN SERVER, LANGUAGE, SCHEMA, SEQUENCE, TYPE

**Comment by mtesauro** [comment]
For quite some time, the DefectDojo install requirement for MySQL/PostgreSQL was an empty DB [1] and a user that can create DB objects in that DB.

Django, the Python framework DefectDojo is written in, supports migrations and DB setup as part of the framework (see [here](https://docs.djangoproject.com/en/4.1/ref/databases/) for details).  When doing DB migrations to a new version of DefectDojo,  columns may be added, tables added, etc.  The cost of restricting the DB user for DefectDojo as you suggest is manually making the needed DB changes that may happen on any new version of the software.  Generally speaking, most users want automated updates, not multi-step manual processes.

The DB user that DefectDojo uses owns only the app's DB (dojodb in godojo's case) so any potential damage is confined to only the apps data.  Presumably in a production setup, sufficient DB backups exist to cover data loss at the DB level.  If not, I'd suggest looking at the many options for PostgreSQL at https://www.postgresql.org/docs/current/backup.html

HTH

[1] Here I mean database as in a named database in a database server.  For PostgreSQL, this means if you do list the databases, one of them will be the database for DefectDojo.  Not to be confused with the entire RDMS installation e.g. MySQL or PostgreSQL
