### ISSUE TITLE
Considers Debian 11 supported but cant perform most operations

### ISSUE THREAD

**Issue by anantshri** [DefectDojo/godojo#59]
Appologies in advance if this sounds like a big rant.

I am surprised this is placed as a one binary doing everything solution but it fails in a lot of ways for me..

1. Debian 11 is not listed as supported so installer should stop it didnt and specifically claimed debian 11 is supported.
2. Postgressql cant be installed coz it doesn't know what to install.
3. Once installation is done it has no directions on whats next.
4. found https://github.com/DefectDojo/godojo/tree/master/docs-and-scripts from the readme not even being highlighted. however once i got the code in place it fails as 
a. screen is not installed 
b. `/opt/dojo/bin/activate` assumption is made about this path with no idea what consideration but this doesnt exist on system.

This could all be because of the fact that debian 11 is not the supported option.  I am also surprised to see that the Ubuntu 22.04 is also not supported. these are LTS releases i would assume they will have better support.
I will use the shell script for setup i assume.

**Comment by mtesauro** [comment]
Debian 11 was never supported nor listed in the [supported OSes](https://docs.google.com/spreadsheets/d/1HuXh3Zr4mrmb6_YmKkDgzl-ZINYZCvVZn31UCqIGpUA/edit?usp=sharing) so I'm not sure why this is worth a "big rant" to use your words.

Ubuntu is a Debian derivative so it _might_ work but I have not tested on Debian 11 so your mileage may vary.

If it doesn't work on Debian 11, I have and will honor a money back guarantee that comes with every copy of godojo.
