### ISSUE TITLE
Failed to run OS command Error

### ISSUE THREAD

**Issue by Barcode91** [DefectDojo/godojo#60]
Hi, I am installing on ubuntu 20.04 using godojo. I am getting the below error. 
defect-dojo version 2.18.3
godojo version  1.1.7

```
Checking connectivity to PostgreSQL
Validating DB connection settings
Note: pg_hba.conf has not been altered by godojo.
      It may need to be updated to allow DefectDojo to connect to the DB.
      Please consult the PostgreSQL documentation for further information.

==============================================================================
  Preparing the OS for DefectDojo installation
==============================================================================

Preparing the OS for DefectDojo...(--*-------) 
##############################################################################
  ERROR: 2023/01/31 14:59:35 - Failed to run OS command /opt/dojo/bin/pip3 install -r /opt/dojo/django-DefectDojo/requirements.txt, error was: exit status 1
##############################################################################
```

**Comment by apeksha2528** [comment]
We are also trying to install latest version of Dojo with Godojo installer on Ubuntu but we are getting same error - ERROR: 2023/02/08 20:04:53 - Failed to run OS command /opt/dojo/bin/pip3 install -r /opt/dojo/django-DefectDojo/requirements.txt, error was: exit status 1
Can someone please help here or provide the guidance so we can resolve this issue?

**Comment by mtesauro** [comment]
@apeksha2528  See answer in #62 

Please don't open multiple tickets - it only slows down getting an answer.

**Comment by mtesauro** [comment]
@Barcode91 I just successfully installed DefectDojo version 2.19.0 on 20.04 with PostgreSQL using godojo version 1.1.9
