### ISSUE TITLE
We are also trying to install latest version of Dojo with Godojo installer on Ubuntu but we are getting same error - ERROR: 2023/02/08 20:04:53 - Failed to run OS command /opt/dojo/bin/pip3 install -r /opt/dojo/django-DefectDojo/requirements.txt, error was: exit status 1

### ISSUE THREAD

**Issue by apeksha2528** [DefectDojo/godojo#62]
We are also trying to install latest version of Dojo with Godojo installer on Ubuntu but we are getting same error - ERROR: 2023/02/08 20:04:53 - Failed to run OS command /opt/dojo/bin/pip3 install -r /opt/dojo/django-DefectDojo/requirements.txt, error was: exit status 1
Can someone please help here or provide the guidance so we can resolve this issue?

_Originally posted by @apeksha2528 in https://github.com/DefectDojo/godojo/issues/60#issuecomment-1423209435_

**Comment by mtesauro** [comment]
You can copy the command you pasted above into the terminal and share the error message (if any) that is displayed.

So take this:
`/opt/dojo/bin/pip3 install -r /opt/dojo/django-DefectDojo/requirements.txt`

and drop it into the host where you're trying to install DefectDojo.  If the error message doesn't help you sort out the issue, drop the error message here.

**Comment by mtesauro** [comment]
You can also try the new release 1.1.9 - I successfully installed on 20.04 with PostgreSQL.
