### ISSUE TITLE
Admin password from dojoConfig.yml not working

### ISSUE THREAD

**Issue by mirasifali** [DefectDojo/godojo#69]
I downloaded godojo release v1.1.9 and ran the godojo file to install defectdojo and then used the scripts dojo-start to start the service. The service is up and running , however I am not able to login with the username and password provided in dojoConfig.yml

**Comment by mtesauro** [comment]
DefectDojo includes a manage.py command to reset a user's password.

Additionally, godojo installs an expect script "setup-superuser.expect" as part of the install process to call manage.py in a non-interactive way.  So you can:

(1) Interactive: Run the command below and answer the prompts:
`cd /opt/dojo/django-DefectDojo && source ../bin/activate && python3 manage.py changepassword  admin`

 OR

(2) Non-Interactive: Run the command below:
`cd /opt/dojo/django-DefectDojo && source ../bin/activate && setup-superuser.expect [put your password here]`
where you replace [put your password here] with the password you want to use. 

For either method, the password provided must meet the configured password requirements or it will be rejected.

Note: The "cd /opt/dojo/django-DefectDojo" and "source ../bin/activate" parts of those command-lines are required to ensure your in the correct path and use the virtual environment in which DefectDojo is installed.
