### ISSUE TITLE
Getting "The redirect URI included is not valid." when trying to login using Gitlab

### ISSUE THREAD

**Issue by mirasifali** [DefectDojo/godojo#70]
I have deployed Defectdojo using Dojo and have made changes to settings.dist.py to enable GitLab Auth following this link https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/#gitlab.

However on clicking on "Login with Gitlab" I am getting the error  "The redirect URI included is not valid"

The redirect_uri in the query string is taking http , where as I have configured a https redirect url in GitLab application.

Also could you please tell where I can find Defectdojo logs so that I could investigate the issue further ? I tried using the '-L' in the screen command but still cant find the logs.

**Comment by mirasifali** [comment]
Manage to resolve a step further by passing SOCIAL_AUTH_REDIRECT_IS_HTTPS = True. However now getting the error "insert or update on table "dojo_product" violates foreign key constraint "dojo_product_sla_configuration_id_05c25ab1_fk_dojo_sla_"
DETAIL:  Key (sla_configuration_id)=(1) is not present in table "dojo_sla_configuration"."

This error is thrown when gitlab auto-import products is set to true

**Comment by mtesauro** [comment]
TBH, this is a configuration of DefectDojo issue rather than an installation issue.

Please open this as an issue in the [application's repo](https://github.com/DefectDojo/django-DefectDojo/issues) or ask on the [OWASP Slack channel](https://github.com/DefectDojo/django-DefectDojo/issues)
